In [22]:
# Lógica de Programção

# Passo 0 - Entender o desafio que você quer resolver

# Passo 1 - Percorrer todos os arquivos da pasta base de dados (Vendas)

import os # Biblioteca para trabalhar com locais de arquivos no pc
import pandas as pd # Biblioteca para trabalhar com bases de dados

lista_arquivo = os.listdir('/content/drive/MyDrive/Programacao/curso-basico-python-hashtag/Vendas')
display(lista_arquivo) # Exibindo a lista formatada

['Devolucoes - Fortaleza.csv',
 'Vendas - Goiás.csv',
 'Vendas - Recife.csv',
 'Devolucoes - Recife.csv',
 'Vendas - Belo Horizonte.csv',
 'Devolucoes - Rio de Janeiro.csv',
 'Vendas - Porto Alegre.csv',
 'Devolucoes - Belo Horizonte.csv',
 'Devolucoes - Goiás.csv',
 'Vendas - Salvador.csv',
 'Vendas - São Paulo.csv',
 'Vendas - Rio de Janeiro.csv',
 'Vendas - Curitiba.csv',
 'Devolucoes - Curitiba.csv',
 'Devolucoes - Salvador.csv',
 'Devolucoes - Porto Alegre.csv',
 'Devolucoes - São Paulo.csv',
 'Vendas - Fortaleza.csv']

In [27]:
tabela_compilada = pd.DataFrame() # Criando uma tabela vazia (Dataframe = Tabela)
dataframes = []

# Passo 2 - importar as bases de dados de vendas
for arquivo in lista_arquivo:
  # verificar se tenho Vendas no arquivo
  if 'Vendas' in arquivo:
    # Importar o arquivo
    tabela = pd.read_csv(f'/content/drive/MyDrive/Programacao/curso-basico-python-hashtag/Vendas/{arquivo}')
    dataframes.append(tabela)

# Passo 3 - Tratar / Compilar as bases de dados
tabela_compilada = pd.concat(dataframes, ignore_index=True)
display(tabela_compilada)

,Unnamed: 0,SKU,Produto,Quantidade Vendida,Primeiro Nome,Sobrenome,Data,Loja,Preco Unitario,Unnamed: 8
0,13,HL4379,Televisão,1,Daniel,Monteiro,5/23/2018,Goiás,2500,NaN
1,19,HL9962,Android,4,Elaine,Santos,7/5/2018,Goiás,3400,NaN
2,45,HL1918,iPhone,5,Lenon,Fernandes,3/31/2018,Goiás,5300,NaN
3,50,HL7348,SmartWatch,1,Vivianne,Rodrigues,8/11/2018,Goiás,1400,NaN
4,97,HL7348,SmartWatch,2,Pedro,Rodrigues,7/26/2018,Goiás,1400,NaN
...,...,...,...,...,...,...,...,...,...,...
9994,9959,HL1918,iPhone,4,Rafael,Carneiro,6/19/2018,Fortaleza,5300,NaN
9995,9974,HL1148,Câmera,2,Thales,Gouvêa,2/20/2018,Fortaleza,2100,NaN
9996,9979,HL1918,iPhone,5,Brenno,Santos,10/18/2018,Fortaleza,5300,NaN
9997,9994,HL4379,Televisão,2,Caio,Ferreira,5/18/2018,Fortaleza,2500,NaN
9998,9995,HL1148,Câmera,5,Kim,Ferreira,3/6/2018,Fortaleza,2100,NaN

In [34]:
# Passo 4 - Calcular o produto mais vendido(em quantidade)
tabela_produtos = tabela_compilada.groupby('Produto').sum()
tabela_produtos = tabela_produtos[['Quantidade Vendida']].sort_values(by='Quantidade Vendida', ascending=False)
display(tabela_produtos)

            Quantidade Vendida
Produto
iPhone                    8974
Televisão                 5931
Notebook                  3249
Android                   3183
SmartWatch                2980
Tablet                    2921
Câmera                    2805

In [35]:
# Passo 5 - calcular o produto que mais faturou(em faturamento)
tabela_compilada['Faturamento'] = tabela_compilada['Quantidade Vendida'] * tabela_compilada['Preco Unitario']
tabela_faturamento = tabela_compilada.groupby('Produto').sum()
tabela_faturamento = tabela_faturamento[['Faturamento']].sort_values(by='Faturamento', ascending=False)
display(tabela_faturamento)

            Faturamento
Produto
iPhone         47562200
Televisão      14827500
Notebook       11371500
Android        10822200
Câmera          5890500
Tablet          4673600
SmartWatch      4172000

In [38]:
# Passo 6 - Calcular a loja/cidade que mais faturou - criar um gráfico/dashboard
tabela_lojas = tabela_compilada.groupby('Loja').sum()
tabela_lojas = tabela_lojas[['Faturamento']].sort_values(by='Loja', ascending=True)
display(tabela_lojas)

                Faturamento
Loja
Belo Horizonte      6480300
Curitiba            7060500
Fortaleza          14087900
Goiás               7441800
Porto Alegre        6868600
Recife              7303000
Rio de Janeiro     14867800
Salvador           13111300
São Paulo          22098300

In [40]:
import plotly.express as px

grafico = px.bar(tabela_lojas, x=tabela_lojas.index, y='Faturamento')
grafico.show()